# Generated by Django 3.0.4 on 2020-04-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200419_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
