# Generated by Django 3.0.4 on 2020-04-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200419_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='asnwer1',
            new_name='answer1',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='asnwer2',
            new_name='answer2',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='asnwer3',
            new_name='answer3',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='asnwer4',
            new_name='answer4',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='asnwer5',
            new_name='answer5',
        ),
    ]
