# Generated by Django 3.0.4 on 2020-04-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200419_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='source'),
        ),
    ]
