# Generated by Django 3.0.4 on 2020-04-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_questions_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Short_type_question',
        ),
    ]
