# Generated by Django 3.0.4 on 2020-04-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_mcq_type_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_type_question',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='source'),
        ),
    ]
