# Generated by Django 3.0.4 on 2020-04-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_mcq_type_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='choice',
            field=models.CharField(default='short', max_length=4),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer4',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer5',
            field=models.TextField(default=''),
        ),
    ]
