# Generated by Django 3.0.4 on 2020-04-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20200428_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
