# Generated by Django 3.0.4 on 2020-04-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_answers_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='choice',
            field=models.CharField(default='short', max_length=5),
        ),
    ]
