# Generated by Django 3.0.4 on 2020-04-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20200428_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer10',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answers',
            name='answer6',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answers',
            name='answer7',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answers',
            name='answer8',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answers',
            name='answer9',
            field=models.TextField(default=''),
        ),
    ]
