# Generated by Django 3.0.4 on 2021-04-14 07:52

from django.conf import settings
from django.db import migrations, models
import front.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0005_remove_profile_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('room', models.CharField(default='00000000', max_length=8)),
                ('author', models.ForeignKey(on_delete=models.SET(front.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
