# Generated by Django 3.0.4 on 2021-04-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='title',
            field=models.CharField(default='Please help me with this', max_length=30),
        ),
    ]
