# Generated by Django 3.0.4 on 2021-04-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_discussion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='room',
            field=models.CharField(default='YAaNIkJS', max_length=8),
        ),
    ]
