# Generated by Django 3.0.4 on 2021-04-14 08:03

from django.db import migrations, models
import front.models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_auto_20210414_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='room',
            field=models.CharField(default=front.models.get_code, max_length=8),
        ),
    ]
