# Generated by Django 3.0.4 on 2021-04-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_comment_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='New announcement', max_length=30),
        ),
    ]
