# Generated by Django 3.0.4 on 2021-04-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_announcement_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='author',
        ),
    ]
