# Generated by Django 3.0.4 on 2021-04-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='topic',
        ),
    ]
