# Generated by Django 3.0.4 on 2021-04-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0017_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='a1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='a2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='a3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='a4',
            field=models.CharField(max_length=50),
        ),
    ]
