# Generated by Django 3.1.7 on 2021-04-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0018_auto_20210419_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bg',
        ),
    ]
