# Generated by Django 3.0.4 on 2021-04-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg',
            field=models.ImageField(default='default.jpg', upload_to='bg_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
